[package]
name = "bin_tree"
version = "0.1.0"
authors = ["jin237 <fgdaojebvoa237@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
